### ISSUE TITLE
$confirm throws error about _t

### ISSUE THREAD

**Issue by smares** [wxsms/uiv#128]
### Version & browser
uiv 0.14.3, Chrome 63

### Which component
MessageBox

### Steps to reproduce the problem
Call $confirm

### Expected behavior
Confirmation modal should appear

### Actual behavior
Console error "Cannot read property '_t' of undefined" called in vue-i18n.esm.js?4d79:174 by uiv.min.js?b442:1

I do have uiv's en-US merged into my locales.

**Comment by wxsms** [comment]
what version of vue-i18n you use? does Modal work?

**Comment by smares** [comment]
7.3.2 and last time I checked, it worked, have to see tomorrow. :/

**Comment by wxsms** [comment]
Confirmed as bug.

**Comment by wxsms** [comment]
Fixed in the new release.

**Comment by smares** [comment]
Updating my dependencies updated vue-i18n to 7.3.3 and the error is back with modals.
